# Generated by Django 5.2.3 on 2025-06-13 11:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="healthrecord",
            name="weight",
            field=models.FloatField(
                blank=True,
                help_text="Weight in kilograms",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        20, message="Weight must be at least 20 kg"
                    ),
                    django.core.validators.MaxValueValidator(
                        300, message="Weight must be less than 300 kg"
                    ),
                ],
            ),
        ),
    ]
