# Generated by Django 5.2.3 on 2025-06-13 11:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0002_healthrecord_weight"),
    ]

    operations = [
        migrations.AddField(
            model_name="healthrecord",
            name="height",
            field=models.FloatField(
                blank=True,
                help_text="Height in centimeters",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        100, message="Height must be at least 100 cm"
                    ),
                    django.core.validators.MaxValueValidator(
                        250, message="Height must be less than 250 cm"
                    ),
                ],
            ),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="weight_goal",
            field=models.FloatField(
                blank=True,
                help_text="Target weight in kilograms",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        20, message="Weight goal must be at least 20 kg"
                    ),
                    django.core.validators.MaxValueValidator(
                        300, message="Weight goal must be less than 300 kg"
                    ),
                ],
            ),
        ),
    ]
