# Generated by Django 5.2.3 on 2025-06-13 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0003_healthrecord_height_healthrecord_weight_goal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="healthrecord",
            name="mood",
            field=models.CharField(
                choices=[
                    ("happy", "😊 Happy"),
                    ("excited", "🤩 Excited"),
                    ("neutral", "😐 Neutral"),
                    ("tired", "😴 Tired"),
                    ("sad", "😢 Sad"),
                    ("stressed", "😰 Stressed"),
                    ("angry", "😠 Angry"),
                    ("anxious", "😰 Anxious"),
                    ("peaceful", "😌 Peaceful"),
                    ("energetic", "⚡ Energetic"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("WEIGHT_GOAL", "Weight Goal"),
                            ("WEIGHT_MILESTONE", "Weight Milestone"),
                            ("DAILY_REMINDER", "Daily Reminder"),
                            ("WEEKLY_SUMMARY", "Weekly Summary"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("scheduled_for", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
