# Generated by Django 5.2.3 on 2025-06-13 13:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0004_alter_healthrecord_mood_notification"),
    ]

    operations = [
        migrations.CreateModel(
            name="FoodRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("BREAKFAST", "Breakfast"),
                            ("LUNCH", "Lunch"),
                            ("DINNER", "Dinner"),
                            ("SNACK", "Snack"),
                        ],
                        max_length=20,
                    ),
                ),
                ("calories", models.PositiveIntegerField()),
                ("protein", models.FloatField(help_text="Protein in grams")),
                ("carbs", models.FloatField(help_text="Carbohydrates in grams")),
                ("fat", models.FloatField(help_text="Fat in grams")),
                ("fiber", models.FloatField(help_text="Fiber in grams")),
                ("description", models.TextField()),
                ("benefits", models.TextField()),
                ("image_url", models.URLField(blank=True, null=True)),
                ("is_vegetarian", models.BooleanField(default=False)),
                ("is_vegan", models.BooleanField(default=False)),
                ("is_gluten_free", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["category", "name"],
            },
        ),
        migrations.AddField(
            model_name="customuser",
            name="age",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Age in years",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        1, message="Age must be at least 1"
                    ),
                    django.core.validators.MaxValueValidator(
                        120, message="Age must be less than 120"
                    ),
                ],
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                help_text="Gender",
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="failed_login_attempts",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
