# Generated by Django 5.2.3 on 2025-06-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "tracker",
            "0005_foodrecommendation_customuser_age_customuser_gender_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="weight_goal",
            field=models.FloatField(
                blank=True, help_text="Target weight in kg", null=True
            ),
        ),
    ]
