# Generated by Django 5.2.3 on 2025-06-17 07:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0006_customuser_weight_goal"),
    ]

    operations = [
        migrations.AddField(
            model_name="healthrecord",
            name="mood_correlation",
            field=models.FloatField(
                blank=True,
                help_text="Correlation with other health metrics",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        -1.0, message="Correlation must be between -1 and 1"
                    ),
                    django.core.validators.MaxValueValidator(
                        1.0, message="Correlation must be between -1 and 1"
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="healthrecord",
            name="mood",
            field=models.CharField(
                choices=[
                    ("EXCELLENT", "Excellent"),
                    ("GOOD", "Good"),
                    ("NEUTRAL", "Neutral"),
                    ("BAD", "Bad"),
                    ("TERRIBLE", "Terrible"),
                ],
                help_text="Select your mood for the day",
                max_length=20,
            ),
        ),
    ]
