# Generated by Django 5.2.3 on 2025-07-04 03:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0007_healthrecord_mood_correlation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="sleep_goal",
            field=models.FloatField(
                blank=True,
                help_text="Target sleep hours per night",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        4, message="Sleep goal must be at least 4 hours"
                    ),
                    django.core.validators.MaxValueValidator(
                        12, message="Sleep goal must be less than 12 hours"
                    ),
                ],
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="water_goal",
            field=models.FloatField(
                blank=True,
                help_text="Target water intake in liters per day",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        1, message="Water goal must be at least 1 liter"
                    ),
                    django.core.validators.MaxValueValidator(
                        10, message="Water goal must be less than 10 liters"
                    ),
                ],
            ),
        ),
    ]
