# Generated by Django 5.2.3 on 2025-07-05 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0009_dailyremindersetting"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="foodrecommendation",
            options={},
        ),
        migrations.RemoveField(
            model_name="foodrecommendation",
            name="benefits",
        ),
        migrations.RemoveField(
            model_name="foodrecommendation",
            name="carbs",
        ),
        migrations.RemoveField(
            model_name="foodrecommendation",
            name="category",
        ),
        migrations.RemoveField(
            model_name="foodrecommendation",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="foodrecommendation",
            name="fat",
        ),
        migrations.RemoveField(
            model_name="foodrecommendation",
            name="fiber",
        ),
        migrations.RemoveField(
            model_name="foodrecommendation",
            name="image_url",
        ),
        migrations.RemoveField(
            model_name="foodrecommendation",
            name="is_gluten_free",
        ),
        migrations.RemoveField(
            model_name="foodrecommendation",
            name="is_vegan",
        ),
        migrations.RemoveField(
            model_name="foodrecommendation",
            name="is_vegetarian",
        ),
        migrations.RemoveField(
            model_name="foodrecommendation",
            name="protein",
        ),
        migrations.RemoveField(
            model_name="foodrecommendation",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="foodrecommendation",
            name="calories",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="foodrecommendation",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
